declare module 'color-string' {
  /** Declaration file generated by dts-gen */

  export function get(string: any): any;

  export namespace get {
    function hsl(string: any): any;

    function hwb(string: any): any;

    function rgb(string: any): any;
  }

  export namespace to {
    function hex(...args: any[]): any;

    function hsl(...args: any[]): any;

    function hwb(...args: any[]): any;

    function keyword(rgb: any): any;

    function rgb(...args: any[]): any;

    namespace rgb {
      function percent(...args: any[]): any;
    }
  }
}
